name: deploy_backend

on:
  push:
    branches: [ main ]
    paths:
    - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: GetResumeCounter
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  DOTNET_VERSION: '6.0'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
    uses: actions/checkout@v3
    uses: azure/login@v1
    with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Setup DotNET  ${{ env.DOTNET_VERSION }} Environment'
    uses: actions/setup-dotnet@v1
    with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
    shell: pwsh
    run:
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/api'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run unit test'
    shell: pwsh
    run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/api'
        dotnet test

    - name: 'Run Azure Functions Action'
    uses: Azure/functions-action@v1
    id: fa
    with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME}}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/output'
        
    